//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersion
    {
        public int AppVersionId { get; set; }
        public string Code { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
    }
}
