//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class Client
    {
        public int ClientId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public bool IsActived { get; set; }
        public bool IsLock { get; set; }
        public bool IsDeleted { get; set; }
        public string PassWork { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public string ConfirmPassword { get; set; }
        public IEnumerable<ClientPayment> ClientPayments { get; set; }

        public int ClientPaymentId { get; set; }    
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }   
        public System.DateTime CreatedDate { get; set; }
        public string PaymentCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public string CreatedUserName { get; set; }
        
        public string SchoolCode { get; set; }
        public string CityCode { get; set; }
        public string DistrictCode { get; set; }
        public string Address { get; set; }
        public IEnumerable<Lesson> ClientLessons { get; set; }
        public IEnumerable<Subject> Subjects { get; set; }
        public IEnumerable<Room>Rooms { get; set; }
        public bool FullLesson { get; set; }
        public bool IsSelected { get; set; }
        public IEnumerable<int> ListId { get; set; }
        public bool ResetLesson { get; set; }
        public bool Approved { get; set; }
        public int ApproverId { get; set; }
        public string ApproverName { get; set; }
        public string MacId { get; set; }
        public string MacIp { get; set; }
        public DateTime ServerTime { get; set; }
    }
}
