//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLesson
    {
        public int ClientLessonId { get; set; }
        public int LessonId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public string Name { get; set; }
        public System.DateTime? EndDate { get; set; }
    }
    public partial class ClientLessonView
    {
        public int ClientLessonViewId { get; set; }
        public int LessonId { get; set; }
        public int ClientId { get; set; }
        public int OpenCount { get; set; }
        public int DownloadCount { get; set; }
        public System.DateTime LastOpen { get; set; }

        public string LastUse { get; set; }
    }
}
