//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int MediaTypeId { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }
        public string NormalImage { get; set; }
        public bool IsFree { get; set; }
        public decimal Price { get; set; }
        public string FileName { get; set; }
        public string DocumentName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public int LessonId { get; set; }
        public DateTime CreatedOn { get; set; }
        public string ChangeOperation { get; set; } 
        public bool IsDownloaded { get; set; }
    }
}

