//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonId { get; set; }
        public int RoomId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
        public string NormalImage { get; set; }
        public string HoverImage { get; set; }
        public string SelectedImage { get; set; }
        public bool IsFree { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public int SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string RoomName { get; set; }
        public IEnumerable<Document>   Documents     { get; set; }
        public string GuideFile { get; set; }

        public string ChangeOperation { get; set; }

        public bool IsDownloaded { get; set; }
        public bool IsSelected { get; set; }

        public int OpenCount { get; set; }
        public int DownloadCount { get; set; } 
        public System.DateTime? LastOpen { get; set; }
        public System.DateTime? EndDate { get; set; }
        public  int Reversion { get; set; }

        public IEnumerable<int> ListId { get; set; }

        public string LastUse { get; set; }
    }
}
