//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {                                             
        public int RightId { get; set; }
        public int? ParentId { get; set; }
        public string RightName { get; set; }
        public bool ShowInMenu { get; set; }
        public string Icon { get; set; }
        public short Order { get; set; }
        public string NameInMenu { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Url { get; set; }
        public bool Status { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public bool Selected { get; set; }
    }
}
