//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
       
        public int RoleId { get; set; }
        public bool RoleActivated { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public List<Right>Rights{ get; set; }
        public bool Selected { get; set; }
    }
}
