//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubjectId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Order { get; set; }
        public string Description { get; set; }
        public string NormalImage { get; set; }
        public string HoverImage { get; set; }
        public string SelectedImage { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }

        public string ChangeOperation { get; set; }
    }
}
