//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {       
    
        public int UserId { get; set; }
        public bool UserActivated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatePassword { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public List<Role> Roles { get; set; }
        public string ConfirmPassword { get; set; }
        public string CityCode { get; set; }
        public string DistrictCode { get; set; }
    }
}
