//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;

    public partial class Client
    {
        public int ClientId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ImageUrl { get; set; }
        public bool IsActived { get; set; }
        public bool IsLock { get; set; }
        public bool IsDeleted { get; set; }
        public string PassWork { get; set; }
        public long RowIndex { get; set; }
        public int TotalRowCount { get; set; }
        public string MacIp { get; set; }
        public bool SavePass { get; set; }
        public DateTime? EndDate { get; set; }
        public bool FullLesson { get; set; }

        public DateTime ServerTime { get; set; }
        public string Address { get; set; }
    }
}
